In [115]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [116]:
df=pd.read_csv('../mlml/dataset/algerian.csv')

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    int64
 14  Rgion        243 non-null    float64
dtypes: float64(8), int64(7)
memory usage: 28.6 KB

In [118]:
X=df.drop('FWI',axis=1)

In [119]:
X

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,Classes,Rgion
0,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0,0.0
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0,0.0
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0,0.0
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0,0.0
4,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,26,9,2012,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,1,1.0
239,27,9,2012,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0,1.0
240,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0,1.0
241,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0,1.0
242,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0,1.0

In [120]:
y=df['FWI']

In [121]:
y

0      0.5
1      0.4
2      0.1
3      0.0
4      0.5
      ...
238    6.5
239    0.0
240    0.2
241    0.7
242    0.5
Name: FWI, Length: 243, dtype: float64

In [122]:
from sklearn.model_selection import train_test_split

In [123]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [124]:
from sklearn.preprocessing import StandardScaler

In [125]:
def correlation(dataset,threshold):
    col_corr=set()
    corr_matrix=dataset.corr()
    for i in range (len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i,j])>threshold:
                colname=corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr

In [126]:
a=df.corr()

In [127]:
len(a)

15

In [128]:
corr_feature=correlation(X_train,0.85)

In [129]:
print(corr_feature)

{'DC', 'BUI'}

In [130]:
X_train.drop(corr_feature,axis=1,inplace=True)

In [131]:
X_test.drop(corr_feature,axis=1,inplace=True)

In [132]:
X_train.shape

(194, 12)

In [133]:
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Rgion
0,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0,0.0
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0,0.0
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0,0.0
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0,0.0
4,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,26,9,2012,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,1,1.0
239,27,9,2012,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,0,1.0
240,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,0,1.0
241,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,0,1.0
242,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,0,1.0

In [134]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [135]:
# train


from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [136]:
y_pred=regressor.predict(X_test)

In [137]:
y_pred

array([ 8.24733596e+00,  7.48785015e+00, -5.58541879e-01,  4.54729645e+00,
        6.99006592e+00,  1.64840814e+00,  1.92438158e+00,  7.98308732e+00,
        1.41150349e+00,  3.58284508e+00,  3.17725550e-01,  9.82171465e+00,
        9.46398290e+00,  1.70090946e+01,  1.85782010e+01,  1.13306317e+00,
        2.14455408e+00,  2.08652684e-02,  7.01156554e+00,  2.81413860e+00,
        1.20931451e+00,  2.70884062e-01,  6.81335380e+00,  4.43255803e-02,
        2.10387427e+01,  5.15784200e+00,  5.65562868e+00,  9.77645366e+00,
       -1.85973080e-01,  9.58561581e+00,  6.77418806e+00, -4.66350280e-01,
        1.04132070e+01,  1.47016502e+01,  1.45686764e+00,  1.34570147e-01,
        1.97335945e+00,  6.12271904e+00, -4.76675128e-01,  1.65234282e-01,
        6.73852202e+00,  2.19930273e+00,  8.79127768e+00, -1.92225980e-01,
        1.55309279e+01,  8.14374240e+00,  8.14030192e+00,  1.28047652e+00,
        1.32290490e+01])

In [138]:
# accuracy
from sklearn.metrics import mean_squared_error,mean_absolute_error

print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(np.sqrt(mean_squared_error(y_test,y_pred)))

0.6509944419630229
0.5392814181571719
0.8068422658506574

In [139]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)

In [140]:
score

0.9785210047261829

# LASSO

In [141]:
from sklearn.linear_model import Lasso

In [142]:
lasso=Lasso()

In [143]:
lasso.fit(X_train,y_train)

Lasso()

In [144]:
y_pred_l=lasso.predict(X_test)

In [145]:
y_pred_l

array([ 7.88909105,  7.51829247,  1.05683695,  5.59521311,  7.19601225,
        2.99047712,  3.30715906,  7.92973493,  2.65285806,  3.94402951,
        1.49545053,  9.95959159,  9.44073609, 15.85531373, 16.42022687,
        2.94983324,  2.57052444, -0.42326091,  7.13525149,  4.07406125,
        2.79367623,  0.82394459,  6.49651495,  0.79636335, 19.34082456,
        5.79451583,  5.89364426,  9.22090638, -0.66175154,  9.89719035,
        6.59978569,  1.06056913,  9.6829589 , 13.13920691,  2.58276684,
        2.28579166,  2.60101763,  6.47535222,  0.36002598,  0.38014286,
        6.35237472,  2.94050278,  8.15702901, -0.56635529, 14.59090328,
        8.01206854,  8.59937477,  2.03651461, 12.51685507])

In [146]:
print(mean_squared_error(y_test,y_pred_l))
print(mean_absolute_error(y_test,y_pred_l))
print(np.sqrt(mean_squared_error(y_test,y_pred_l)))

1.726042726921603
1.0093958815851467
1.3137894530409364

In [147]:
score_l=r2_score(y_test,y_pred_l)
score_l

0.9430507218123662

# RIDGE

In [148]:
from sklearn.linear_model import Ridge
ridge=Ridge()

In [149]:
ridge.fit(X_train,y_train)

Ridge()

In [150]:
y_pred_r=ridge.predict(X_test)

In [151]:
print(mean_squared_error(y_test,y_pred_r))
print(mean_absolute_error(y_test,y_pred_r))
print(np.sqrt(mean_squared_error(y_test,y_pred_r)))

0.6728556028799642
0.5537275379145166
0.8202777595912034

In [152]:
score_r=r2_score(y_test,y_pred_r)

In [153]:
score

0.9785210047261829

# ELASTIC NET REGRESSION

In [154]:
from sklearn.linear_model import ElasticNet

In [155]:
en=ElasticNet()

In [156]:
en.fit(X_train,y_train)

ElasticNet()

In [157]:
y_pred_en=en.predict(X_test)

In [158]:
print(mean_squared_error(y_test,y_pred_en))
print(mean_absolute_error(y_test,y_pred_en))
print(np.sqrt(mean_squared_error(y_test,y_pred_en)))

4.045350281241074
1.648350762574408
2.011305616071579

In [159]:
scor_en=r2_score(y_test,y_pred_en)

In [160]:
scor_en

0.86652718676107

In [161]:
import pickle 
pickle.dump(scaler, open('../models/scaler.pkl', 'wb'))
pickle.dump(ridge, open('../models/ridge.pkl', 'wb'))